name: Build-On-Trigger
on: [workflow_dispatch, push]
jobs:
  buildWindows:
    runs-on: windows-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.1.5
      # Runs a set of commands using the runners shell
      - name: create GJKeys.hx
        run: echo "package;class GJKeys{public static var id:Int = ${{ secrets.GAMEID }};public static var key:String = '${{ secrets.GAMEKEY }}';}" > source/GJKeys.hx
      - name: script run line haha
        run: |
          Install project dependencies
          haxelib install lime 7.9.0
          RefreshEnv
          haxelib install openfl
          haxelib install flixel
          haxelib run lime setup flixel
          haxelib run lime setup
          haxelib install flixel-tools
          haxelib run flixel-tools setup -y # Can't do this since it asks [y/n] even with -y argument! Stupid
          haxelib install flixel-addons
          haxelib install flixel-ui
          haxelib install hscript
          haxelib install newgrounds
          haxelib install flixel-addons
          haxelib git faxe https://github.com/uhrobots/faxe
          haxelib git polymod https://github.com/larsiusprime/polymod.git
          haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
          haxelib git extension-webm https://github.com/KadeDev/extension-webm
          haxelib run lime rebuild extension-webm windows
          haxelib install actuate 
          haxelib git systools https://github.com/haya3218/systools
          haxelib run lime rebuild systools windows
          haxelib git linc_luajit https://github.com/nebulazorua/linc_luajit.git
          haxelib git hxvm-luajit https://github.com/nebulazorua/hxvm-luajit
          haxelib list
          
      - name: Ok now we acutally compile
        run: haxelib run lime build windows
          
      - name: Compress
        run: tar -czf bin.tar.gz export/release/windows/bin
          
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Windows Build
          path: bin.tar.gz
          retention-days: 1
          

#       - name: Email-Results
#         if: success()
#         uses: dawidd6/action-send-mail@v3
#         with:
#           username: ${{ secrets.MAIL_UN }}
#           password: ${{ secrets.MAIL_PW }}
#           server_address: smtp.gmail.com
#           server_port: 465
#           to: ${{ secrets.EMAIL }}
#           from: Github Actions
#           secure: true
#           subject: ${{ github.repository }} success 
#           body: |
#             Build job of ${{github.repository}} completed successfully!
            
#             You can check how it went with the link below!
            
#             https://github.com/TentaRJ/Note-Test/actions/workflows/build.yml
#           priority: high
#       - if: failure()
#         uses: dawidd6/action-send-mail@v3
#         with:
#           username: ${{ secrets.MAIL_UN }}
#           password: ${{ secrets.MAIL_PW }}
#           server_address: smtp.gmail.com
#           server_port: 465
#           to: ${{ secrets.EMAIL }}
#           from: Github Actions
#           secure: true
#           subject: ${{ github.repository }} failure 
#           body: |
#             Build job of ${{github.repository}} failed! You idiot! 
            
#             Check what went wrong!
            
#             https://github.com/TentaRJ/Note-Test/actions/workflows/build.yml
#           priority: high
